version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html/
      - cp 404.html /var/www/html/
      - cp blog-single.html /var/www/html/
      - cp portfolio-details.html /var/www/html/
      - cp style.css /var/www/html/
      - cp -r css /var/www/html/
      - cp -r js /var/www/html/
      - cp -r mail /var/www/html/


  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'
